### ISSUE TITLE
Adjust /user to not include the global FYI

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#548]
Global FYI shows up on /user pages. Remove from the styling.

![site alert on on slash user](https://cloud.githubusercontent.com/assets/20731897/24512539/d467136c-153c-11e7-88d0-c9b9befc5574.PNG)

**Comment by matthewcrist** [comment]
## Testing steps

 - Make sure there is a site alert published
 - Visit /user
 - Verify that layout is correct with alert

**Comment by reillyzlab** [comment]
Still showing up on /user for both sites.

**Comment by matthewcrist** [comment]
It was still going to show up. The layout is fixed.

**Comment by reillyzlab** [comment]
Still showing up on boston.gov

Is this something we should include in the exclusions list in admin instead?

**Comment by matthewcrist** [comment]
We had decided to keep showing it, but just fix the layout.
