### ISSUE TITLE
Email validation one email signup widgets is broken when missing "."

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/boston.gov#884]
What is happening

When a user signs up for email but doesn't include the "." in their address, the widget hangs on "Loading" 

![issue](https://user-images.githubusercontent.com/20726937/31199682-2458a71e-a926-11e7-9bb4-c235e8e17bc6.JPG)

What should happen

It should show an error to the user indicating what the problem is per #715

**Comment by reillyzlab** [comment]
@joshuagee can you clarify further what you mean?

is it the dot before or after @ sign?

**Comment by joshuagee** [comment]
@reillyzlab If they don't structure the url correctly. So joshua.gee@bostongov instead of joshua.gee@boston.gov

**Comment by matthewcrist** [comment]
This is fixed on production @joshuagee. Please test and close if you agree.

**Comment by joshuagee** [comment]
@matthewcrist I am still seeing the same error on the component on the front page and a sidebar component I tested on https://www.boston.gov/departments/transportation/neighborhood-slow-streets

**Comment by joshuagee** [comment]
@matthewcrist NM -- it was cacheing.
